openapi: 3.0.0
info:
  title: OpenWeatherMap API
  version: '2.5'
  description: 'Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results. This is an update.'
  contact:
    name: Support
    url: 'https://openweathermap.org/api'
    email: some_email@gmail.com
  termsOfService: 'https://openweathermap.org/terms'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
    description: prod
paths:
  /weather:
    get:
      summary: weather
      tags:
        - Weather endpoints
      responses: {}
      operationId: get-weather
      description: 'Access current weather data for any location on earth including over 200,000 frequently updaeed based on global models and data from more than 40,000.'
      parameters:
        - schema:
            type: string
          in: query
          name: zip
          description: '**Zip code**. Search by zip code. *Example: 42420'
        - schema:
            type: string
          in: query
          name: units
          description: '*Example: imperial*. Possible values "standard"'
      security:
        - app_id: []
    parameters: []
components:
  schemas:
    unauthorized_response:
      title: unauthorized_response
      type: object
      properties:
        id:
          type: string
        cod:
          type:
            - string
            - integer
        message:
          type: string
      required:
        - cod
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
